{% set name = "gmatelastoplasticqpot" %}
{% set version = "0.4.0" %}
{% set sha256 = "ad510dcca2ca93eafc0ebf8809cbcb16f397bd8827ad377bc6949df3b8c189f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlasticQPot/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
  run:
    - xtensor

test:
  commands:
    - test -d ${PREFIX}/include/GMatElastoPlasticQPot  # [unix]
    - test -f ${PREFIX}/include/GMatElastoPlasticQPot/Cartesian2d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GMatElastoPlasticQPot/GMatElastoPlasticQPotConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GMatElastoPlasticQPot\Cartesian2d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GMatElastoPlasticQPotConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GMatElastoPlasticQPot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Elasto-plastic model based on a manifold of quadratic potentials (C++ header-only library).'
  description: 'Elasto-plastic model based on a manifold of quadratic potentials (C++ header-only library).'
  doc_url: https://github.com/tdegeus/GMatElastoPlasticQPot
  dev_url: https://github.com/tdegeus/GMatElastoPlasticQPot

extra:
  recipe-maintainers:
    - tdegeus
