{% set org = "tdegeus" %}
{% set name = "GMatElastoPlasticQPot" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bcff14a415f4324829f0f4563ccff1d9f8e9ae8287c8fdd15eaf767922b78e37

build:
  number: 0

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - gmattensor <0.8.0
        - qpot
        - xtensor
      run:
        - gmattensor <0.8.0
        - qpot
        - xtensor

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/Cartesian2d.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\Cartesian2d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      skip: true  # [python_impl == 'pypy']

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja
      host:
        - gmattensor <0.8.0
        - numpy *
        - pip
        - pybind11
        - pybind11-abi
        - python
        - qpot
        - scikit-build
        - setuptools_scm
        - xtensor
        - xtensor-python
      run:
        - numpy *
        - python

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
        - python -c "import {{ name }}; assert {{ name }}.version() == '{{ version }}'"
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic model based on a manifold of quadratic potentials (C++ header-only library).
  description: Elasto-plastic model based on a manifold of quadratic potentials (C++ header-only library).
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
