{% set org = "tdegeus" %}
{% set name = "GMatElastoPlasticQPot" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8b3d354096b20b0080288de2685b2a2c330235bc268a9e054363bf31c4a92db6

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - setuptools_scm
    - xtensor
    - qpot
    - gmattensor
  run:
    - xtensor
    - qpot
    - gmattensor

test:
  commands:
    - test -d ${PREFIX}/include/{{ name }}  # [unix]
    - test -f ${PREFIX}/include/{{ name }}/Cartesian2d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\{{ name }}\Cartesian2d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic model based on a manifold of quadratic potentials (C++ header-only library).
  description: Elasto-plastic model based on a manifold of quadratic potentials (C++ header-only library).
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
